POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "lauti",
    "email": "lauti@gmail.com",
    "password": "lauti123"
}

POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "lauti",
    "password": "lauti123"
}

POST http://localhost:3000/api/auth/login-sales-manager HTTP/1.1
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin123"
}

POST http://localhost:3000/api/auth/logout HTTP/1.1

POST http://localhost:3000/api/auth/verify HTTP/1.1